### ISSUE TITLE
Disputes, Slashing, and Rewards

### ISSUE THREAD

**Issue by Sophia-Gold** [paritytech/roadmap#22]
[Tracking issue](https://github.com/paritytech/polkadot/issues/6388)
[Project board](https://github.com/orgs/paritytech/projects/64)

Q2 milestones:

- [ ] Implement past-session slashing (https://github.com/paritytech/polkadot/issues/5947)
- [ ] Finalize time overruns spec (https://github.com/paritytech/polkadot/issues/6510)
- [ ] Finalize validator disabling spec (https://github.com/paritytech/polkadot/issues/5948)

Q3 milestones:

- [ ] Implement validator disabling
- [ ] Develop parachain consensus rewards spec with W3F research

Q4 milestones:

- [ ] Implement time overruns
- [ ] Implement parachain consensus rewards
